name: publish on npmjs

on:
  release:
   types: [created]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install -y android-tools-adb
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8.14.0
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/
        cache: 'pnpm'
    - name: run pnpm install
      run: pnpm install --frozen-lockfile
    - run: pnpm run build
    - run: pnpm publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
