name: Node.js CI

on:
  push:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "test/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - ".github/workflows/test.yml"
  pull_request:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "test/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - ".github/workflows/test.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12, 14, 16, 18]

    steps:
    - run: sudo apt-get install -y android-tools-adb
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 6.32.23
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: run pnpm install
      run: pnpm install --frozen-lockfile
    - run: pnpm run test
